/* This file is auto-generated using the IRQN tool. Do not modify. */

#ifndef IRQN_HANDLER

#include <stm32l0xx_it.h>

#else

IRQN_HANDLER(-14, NonMaskableInt)
IRQN_HANDLER(-13, HardFault)
SKIP_HANDLER(-12)
SKIP_HANDLER(-11)
SKIP_HANDLER(-10)
SKIP_HANDLER(-9)
SKIP_HANDLER(-8)
SKIP_HANDLER(-7)
SKIP_HANDLER(-6)
IRQN_HANDLER(-5, SVC)
SKIP_HANDLER(-4)
SKIP_HANDLER(-3)
IRQN_HANDLER(-2, PendSV)
IRQN_HANDLER(-1, SysTick)
IRQN_HANDLER(0, WWDG)
SKIP_HANDLER(1)
IRQN_HANDLER(2, RTC)
IRQN_HANDLER(3, FLASH)
IRQN_HANDLER(4, RCC)
IRQN_HANDLER(5, EXTI0_1)
IRQN_HANDLER(6, EXTI2_3)
IRQN_HANDLER(7, EXTI4_15)
SKIP_HANDLER(8)
IRQN_HANDLER(9, DMA1_Channel1)
IRQN_HANDLER(10, DMA1_Channel2_3)
IRQN_HANDLER(11, DMA1_Channel4_5_6_7)
IRQN_HANDLER(12, ADC1)
IRQN_HANDLER(13, LPTIM1)
SKIP_HANDLER(14)
IRQN_HANDLER(15, TIM2)
SKIP_HANDLER(16)
SKIP_HANDLER(17)
SKIP_HANDLER(18)
SKIP_HANDLER(19)
IRQN_HANDLER(20, TIM21)
SKIP_HANDLER(21)
IRQN_HANDLER(22, TIM22)
IRQN_HANDLER(23, I2C1)
SKIP_HANDLER(24)
IRQN_HANDLER(25, SPI1)
SKIP_HANDLER(26)
SKIP_HANDLER(27)
IRQN_HANDLER(28, USART2)
IRQN_HANDLER(29, LPUART1)

#endif

